
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "memebot"
version = "0.0.2"
requires-python = ">=3.11"

[tool.setuptools]
packages = ["memebot"]
